// <auto-generated />
using System;
using AspNetCore_EFCore_CodeFirst.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore_EFCore_CodeFirst.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNetCore_EFCore_CodeFirst.Models.Categoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nome = "Poesia"
                        });
                });

            modelBuilder.Entity("AspNetCore_EFCore_CodeFirst.Models.Livro", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ID");

                    b.HasIndex("CategoriaID");

                    b.HasIndex("Titulo")
                        .HasDatabaseName("IDX_livro_Titulo");

                    b.ToTable("Livro", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Autor = "Manoel de Barros",
                            CategoriaID = 1,
                            DataEntrada = new DateTime(2025, 1, 11, 1, 43, 14, 21, DateTimeKind.Local).AddTicks(5842),
                            Preco = 25.00m,
                            Quantidade = 10,
                            Titulo = "O Guardador de Águas"
                        },
                        new
                        {
                            ID = 2,
                            Autor = "Manoel de Barros",
                            CategoriaID = 1,
                            DataEntrada = new DateTime(2025, 1, 11, 1, 43, 14, 21, DateTimeKind.Local).AddTicks(5853),
                            Preco = 25.00m,
                            Quantidade = 16,
                            Titulo = "O Livro das Ignorãças"
                        },
                        new
                        {
                            ID = 3,
                            Autor = "Thiago de Mello",
                            CategoriaID = 1,
                            DataEntrada = new DateTime(2025, 1, 11, 1, 43, 14, 21, DateTimeKind.Local).AddTicks(5855),
                            Preco = 25.00m,
                            Quantidade = 54,
                            Titulo = "Faz escuro mais eu canto"
                        },
                        new
                        {
                            ID = 4,
                            Autor = "Orides Fontela",
                            CategoriaID = 1,
                            DataEntrada = new DateTime(2025, 1, 11, 1, 43, 14, 21, DateTimeKind.Local).AddTicks(5855),
                            Preco = 25.00m,
                            Quantidade = 22,
                            Titulo = "Poesia Completa"
                        },
                        new
                        {
                            ID = 5,
                            Autor = "Joseph Campbell",
                            CategoriaID = 1,
                            DataEntrada = new DateTime(2025, 1, 11, 1, 43, 14, 21, DateTimeKind.Local).AddTicks(5921),
                            Preco = 25.00m,
                            Quantidade = 10,
                            Titulo = "O Poder do Mito"
                        },
                        new
                        {
                            ID = 6,
                            Autor = "Thiago de Mello",
                            CategoriaID = 1,
                            DataEntrada = new DateTime(2025, 1, 11, 1, 43, 14, 21, DateTimeKind.Local).AddTicks(5922),
                            Preco = 25.00m,
                            Quantidade = 10,
                            Titulo = "Poesia comprometida com a minha e a tua vida"
                        });
                });

            modelBuilder.Entity("AspNetCore_EFCore_CodeFirst.Models.Livro", b =>
                {
                    b.HasOne("AspNetCore_EFCore_CodeFirst.Models.Categoria", "Categoria")
                        .WithMany("Livros")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AspNetCore_EFCore_CodeFirst.Models.Categoria", b =>
                {
                    b.Navigation("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
